### ISSUE TITLE
Support Library update?

### ISSUE THREAD

**Issue by BamiGorengo** [GoogleChromeLabs/svgomg-twa#10]
@andreban you posted in https://github.com/GoogleChromeLabs/svgomg-twa/issues/4#issuecomment-462755224 this:

One possible cause is the version of the Support Library being used. The version in the demo had an issue that showed the URL Bar when the TWA is opened and Chrome is being cold-started. Updating the Support Library version fixes the issue:

```
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.github.GoogleChrome.custom-tabs-client:customtabs:7ab7178ae0'
}
```

If the Support Library is outdated or contains a bug, can you please update this in the repository? Then i can remove my fork of this repo and can link the original source repo in [my blog article](https://medium.com/@svenbudak/this-twa-stuff-rocks-finally-i-got-my-pwa-on-google-play-store-b92fe8dae31f)

**Comment by andreban** [comment]
The sample has been updated with a version of the Support Library that fixes this issue and allows changing the status-bar colour on #8.

**Comment by BamiGorengo** [comment]
oh awesome! Thank you! :)
