### ISSUE TITLE
TWA top url bar not hiding 

### ISSUE THREAD

**Issue by spike99** [GoogleChromeLabs/svgomg-twa#100]
The bar with url does not disappear I signed the application. I made a folder in public_html on my host with folder and file .well-known/assetlinks.json 
Work when I install the application from my site directly. but when I upload the application to google play store and install it again the top bar appears. Why?

**Comment by FluorescentHallucinogen** [comment]
> Why?

Because Google Play re-sign APK and `assetlinks.json` should be updated. Read more: https://developers.google.com/web/updates/2019/08/twas-quickstart#play-store-signing

**Comment by andreban** [comment]
The best place to ask Trusted Web Activity questions is in this [StackOverflow tag](https://stackoverflow.com/questions/tagged/trusted-web-activity). Closing the issue, as it's not related specifically to svgomg-twa.
