### ISSUE TITLE
[Question] Adsense in PWA/TWA

### ISSUE THREAD

**Issue by matthewhartman** [GoogleChromeLabs/svgomg-twa#105]
Hi Guys,

Hope you're all keeping well.

Just had a general question about integrating Adsense into a PWA/TWA app - just wondering if it's currently possible? - if so, could you please point me in the right direction for documentation or an example.

Thanks again and looking forward to hearing back from you soon.

Cheers,

Matt

**Comment by andreban** [comment]
Hi @matthewhartman,

I have posted / answered the question for you on StackOverflow: https://stackoverflow.com/questions/62017395/is-it-possible-to-use-adsense-in-a-pwa-trusted-web-activity-app/62017543#62017543

Andre

**Comment by matthewhartman** [comment]
Thanks man!!

**Comment by FANMixco** [comment]
This is a real problem. "Valuable Inventory: No content"
