### ISSUE TITLE
Setting Notifications to true still asks for permission from user

### ISSUE THREAD

**Issue by successful-fella** [GoogleChromeLabs/svgomg-twa#106]
Hello,

I saw in this [issue](https://github.com/GoogleChromeLabs/svgomg-twa/issues/60#issuecomment-577087204) that user don't have to click allow by themselves. I haven't override any class and directly had set enableNotifications in gradle to true. I'm not immediately requesting for permission on application open, I request it when user logs in their account.
In this case I was expecting to have permission true but when I verified it in Chrome it says default. Blocking and allowing set permission accordingly in Chrome.

I'm requesting notification through JavaScript Notification API, I made no changes in service worker. What could be that I'm missing?

Thanks.

**Comment by andreban** [comment]
Would you mind filing this issue against https://github.com/GoogleChrome/android-browser-helper? (this repository is just the sample app and doesn't use notifications itself). 

It would also help if the Android device model and version, the Chrome version and version of the library used in the project (inside app/build.gradle) are being used.

**Comment by Husseinhj** [comment]
I don't understand, is there any way to act notification like _Android native_?

**For instance:**
1. In Android native, notification permission by default is granted. 

2. In Android native, when users click on notification application will be opened. 
(But in TWA, it's different behavior and the Chrome browser opened not the application.)

3. Can we detect uninstall TWA application like Android Native? In this version of TWA, When users uninstalled the app user 
(still getting notification from the Chrome browser and gets a success response from VAPID.)

**Comment by successful-fella** [comment]
@Husseinhj  Haven't figured out the first, but for second you may want to check the protocol and exact service worker registered URL (for example if it's https://abc.com/test, notification URL should go along same https://abc.com/test/$1/...)
I can confirm that clicking on notification properly opens in app instead of Google Chrome. Same happens when clicking application URL from other source such as Telegram, Twitter, etc.

**Comment by Husseinhj** [comment]
@successful-fella 
Thanks for your swift answer.

For the WEB users on Android, the user should grant notification permission by pressing on the **allowed** button. In Android native application user notifications **by default are granted** and engagement between users will be easier because they always are opted-in on Notification channels, So it's a very important issue to have opted-in users like Android native app.


> Same happens when clicking application URL from other source such as Telegram, Twitter, etc.

I did a test in TWA and did not open my application just open Chrome application. I think you are talking about **deep-link** in android, am I right?

**Comment by successful-fella** [comment]
@Husseinhj No, I don't think this is deep linking. What happens is Chrome opens the application when request from external app or webpush matches service worker URL pattern (at least this is what I think how it works). Maybe you should try adjusting the URL. It's working for me though.

Also yes allowing notification in app is a bad user experience and [notification delegation](https://github.com/GoogleChromeLabs/svgomg-twa/issues/60#issuecomment-577087204) is a solution. I can't get it work though.

**Comment by Husseinhj** [comment]
> Also yes allowing notification in-app is a bad user experience and [notification delegation](https://github.com/GoogleChromeLabs/svgomg-twa/issues/60#issuecomment-577087204) is a solution. I can't get it to work though.

Me neither. I try to enable `enableNotifications` but it doesn't work and I'm confused about that.

> No, I don't think this is deep linking. What happens is Chrome opens the application when request from external app or webpush matches service worker URL pattern (at least this is what I think how it works). Maybe you should try adjusting the URL. It's working for me though.

I'll check this out. Thanks.

@successful-fella Do you have any idea about uninstalling application tracking in TWA?
(I'm sure in WEB to uninstall mean's user unregister service worker by clearing their browser cache)

**Comment by andreban** [comment]
This repository is deprecated and we're not actively looking into issues. here. Please file issue against https://github.com/GoogleChrome/android-browser-helper.
