### ISSUE TITLE
Hide div in twa in-app browser

### ISSUE THREAD

**Issue by bsde1234** [GoogleChromeLabs/svgomg-twa#107]
Hi,
I have asked a question in https://stackoverflow.com/questions/61517599/hide-div-in-a-custom-tab-opened-from-a-trusted-web-activity 
Let me explain a littile bit more.

My twa website is https://www.monsoonmalabar.com/
In the above site there is a link to external site which is https://keralapsc.monsoonmalabar.com/ when clicking this link in twa app, this link openes in in-app browser. In that in-app browser(website: https://keralapsc.monsoonmalabar.com) there is a button floats left side with link `https://play.google.com/store/apps/details?id=com.monsoonmalabar.app`. I want to hide that link(button) when user using twa(in-app browser). According to your suggestion in the stackoverflow site, I added the external link as https://keralapsc.monsoonmalabar.com/?hideDiv=true  
And added a code in external site as  
```
<script>
  var url_string = window.location.href; //window.location.href
var url = new URL(url_string);
if(url.searchParams.get("hideDiv")) {
  document.write('<div></div>');
} else {
  document.write('<div id="play_button"><a class="btn_openinapp" data-attr="btn_openinapp" href="https://play.google.com/store/apps/details?id=com.monsoonmalabar.app" style="left: 0px;">ആപ്പിൽ തുറക്കുക</a></div>');
}

</script>
```

Now what happenes is during the first visit from twa(wich have hideDive=true) the button disappears. But when I continue to surf external site by going to another page in that external site button shows again. May be I didn't understand you correctly. Can you please explain a little bit more with codes. I am new to coding. My twa app is https://play.google.com/store/apps/details?id=com.monsoonmalabar.app

Below is the screenshot of external link marked.

![Screenshot_20200622_190054](https://user-images.githubusercontent.com/35421561/85293667-4a7fe080-b4bb-11ea-8754-1e3a2fe9ba19.jpg)

Thanks.

**Comment by andreban** [comment]
This repository is deprecated. Please, follow-up on StackOverflow.
