### ISSUE TITLE
Running the TWA from a Chromebook just opens the URL in the browser and not a standalone window

### ISSUE THREAD

**Issue by sensoryapphouse** [GoogleChromeLabs/svgomg-twa#108]
**Describe the bug**
When I download a TWA built like this project on Chromebooks it only launches the URL inside the Chrome browser and not as a standalone webview. If I install as a PWA then it runs correctly inside a standalone browser. The website is also not cached while running from the TWA unlike the PWA.

**To Reproduce**
1. Download https://play.google.com/store/apps/details?id=com.sesnsoryapphouse.electra&hl=en on a Chromebook 
2. Open the application
3. See it opening inside Chrome Browser

**Expected behavior**
The TWA runs as a standalone application like the PWA or the TWA on Android

**Comment by PEConn** [comment]
We're working on supporting TWAs in ChromeOS ([bug here](https://bugs.chromium.org/p/chromium/issues/detail?id=1026472)). What version of ChromeOS are you using?

**Comment by sensoryapphouse** [comment]
Chrome Version 83.0.4103.112 32 bit.

**Comment by PEConn** [comment]
Support should be coming in Chrome 85. You'll also need to make sure that your TWA was created with an up to date version of `android-browser-helper`. If you create it through [bubblewrap](https://github.com/GoogleChromeLabs/bubblewrap), that should work.

**Comment by sensoryapphouse** [comment]
I will try this thank you.

**Comment by sensoryapphouse** [comment]
Mark as fixed as of Chrome 85 :+1:
