### ISSUE TITLE
Update Android SDK studio to version 30

### ISSUE THREAD

**Issue by cxspxr** [GoogleChromeLabs/svgomg-twa#113]
**Describe the bug**
Android Studio default SDK version is now 30, whereas this project uses 29, I think it should be updated.

**To Reproduce**
1. Download latest Android Studio
2. Try to run this project with SDK version 30

**Expected behavior**
No crashes

**Comment by PEConn** [comment]
Heya,

This project isn't maintained any more - it has been superseded by [android-browser-helper](https://github.com/GoogleChrome/android-browser-helper).

I had a look through our newer repo and [we mostly use version 30](https://github.com/GoogleChrome/android-browser-helper/search?q=compileSdkVersion), although one or two of the demos are version 29. I filed [a bug](https://github.com/GoogleChrome/android-browser-helper/issues/240) in that repo to track it.
