### ISSUE TITLE
Android Browser Helper version

### ISSUE THREAD

**Issue by rafaeldev** [GoogleChromeLabs/svgomg-twa#118]
Hello everyone!

Today the [android-browser-helper](https://github.com/GoogleChrome/android-browser-helper) version have some fixes about launch screen which I think is important to stay in this example project 

https://github.com/GoogleChrome/android-browser-helper/releases

**Comment by rafaeldev** [comment]
https://github.com/GoogleChrome/android-browser-helper/pull/297

**Comment by PEConn** [comment]
Hey,

This project is pretty much deprecated - people should use android-browser-helper or bubblewrap (previously llama-pack, which is based on android-browser-helper) instead.
