### ISSUE TITLE
Support for Crashlytics

### ISSUE THREAD

**Issue by Dvelezs94** [GoogleChromeLabs/svgomg-twa#12]
Some devices are crashing with a blank screen or just freeze, so I want to add crashlytics but I cannnot find the file MainActivity.java, which leads me to think that it is not supported here, can you please confirm?

Thanks

**Comment by andreban** [comment]
LauncherActivity.java is part of the Support Library and can be found [here](https://github.com/GoogleChrome/custom-tabs-client/blob/master/customtabs/src/android/support/customtabs/trusted/LauncherActivity.java).

Regarding the crashing with a blank screen / freeze, we just released a new version of the Support Library that should fix crashes when the user's default browser doesn't support TWA, and it can be enabled with the version below:

```gradle
implementation 'com.github.GoogleChrome.custom-tabs-client:customtabs:d08e93fce3'
```
If you still see issues with blank screen / freezes with this new version, please let us know, and we'll investigate.

Andre

**Comment by Dvelezs94** [comment]
thank you @andreban ! it does work. It shows the top address bar but at least it doesnt crash anymore. Just FYI, it seems that the people having these issues were on samsung devices (some on s9). I dont know if samsung does not support TWA but well i guess its just matter of time for their browser to support it.

Thank you very much for the fix you rock!
