### ISSUE TITLE
Asset links configured correctly but still opening in a tab.

### ISSUE THREAD

**Issue by LookRain** [GoogleChromeLabs/svgomg-twa#16]
Hi I have tried building my PWA to apk but it still opens the app in a tab view after many attemps. Here's what I'm currently doing:
- I have my PWA at `https://staging.ratex.co/home`, 
- my assetlinks is at `https://staging.ratex.co/.well-known/assetlinks.json`, and it passes the 'Statement List Generator and Tester' test
- my `manifestPlaceholders` is: 
```
manifestPlaceholders = [
                hostName: "staging.ratex.co",
                defaultUrl: "https://staging.ratex.co/home",
                launcherName: "RateX Lite",
                assetStatements: '[{ "relation": ["delegate_permission/common.handle_all_urls"], ' +
                        '"target": {"namespace": "web", "site": "https://staging.ratex.co/home"}}]'
        ]
```

Is there anything I'm doing wrong? Would really appreciate the help. Thanks!

**Comment by andreban** [comment]
The `assetStatements` section needs to have only the origin on the `site` attribute. Try replacing `https://staging.ratex.co/home` with `https://staging.ratex.co` in that section.

Would you be able to move this question to StackOverflow? There's a [specific tag for Trusted Web Activities](https://stackoverflow.com/questions/tagged/trusted-web-activity/) and it makes easier for other developers running into similar issues to find the solution.

**Comment by LookRain** [comment]
@andreban Hi thanks for the reply. I've actually tried both for the `site` attribute, neither of them worked.
I've given up on converting my PWA to apk, guess I'll wait until there's more documentation and hints for possible errors for this technology.

**Comment by andreban** [comment]
Hi @LookRain, the Digital AssetLinks part can be tricky to get right, as it has a few moving pieces and they all need to match correctly. I'm happy to help figure out what is missing in your implementation. Would you be able to share and APK I can look at?
