### ISSUE TITLE
Detecting if the PWA is installed.

### ISSUE THREAD

**Issue by Gedoba** [GoogleChromeLabs/svgomg-twa#18]
Hey, I'm trying to detect if PWA is installed using TWA. But this answer does not work in this case. 
https://stackoverflow.com/questions/21125337/how-to-detect-if-web-app-running-standalone-on-chrome-mobile
(It does in case of nonTWA PWA). Any ideas?

**Comment by andreban** [comment]
Hi @Gedoba.

Does this help: https://stackoverflow.com/questions/54580414/how-can-i-detect-if-my-website-is-running-inside-a-trusted-web-actvity

**Comment by Gedoba** [comment]
It works indeed!
To summarize I used: document.referrer.includes('android-app://'), which returns true if it comes from TWA.

**Comment by andreban** [comment]
Closing this, as the question has been answered.

**Comment by sjafarianm** [comment]
> It works indeed!
> To summarize I used: document.referrer.includes('android-app://'), which returns true if it comes from TWA.

I inspect my TWA with remote debugging and it appears that document.referrer is not like 'android-app://' . It is something like https://sitename.com/... . Any idea why??

**Comment by PEConn** [comment]
The referrer will only be android-app:// for the first navigation, maybe you're inspecting the TWA after subsequent navigations?

**Comment by andreban** [comment]
@sjafarianm If you can share the APK or the start_url, I'd be happy to take a look.

**Comment by sjafarianm** [comment]
> The referrer will only be android-app:// for the first navigation, maybe you're inspecting the TWA after subsequent navigations?

That's right. Thank you.
