### ISSUE TITLE
Splash screen doesn't work

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [GoogleChromeLabs/svgomg-twa#24]
Pull request #23 was merged into `master` recently. I've cloned the `master` branch and built the app, but I don't see the splash screen.

@andreban Have you tested the PR before merging?

**Comment by andreban** [comment]
Are you using Chrome Canary for testing?

**Comment by FluorescentHallucinogen** [comment]
I've changed the WebView provider in Android developer options from Chrome to Chrome Canary, but it didn't help.

Only removing (freezing) Chrome Stable helps.

**Comment by andreban** [comment]
@FluorescentHallucinogen 

Trusted Web Activities are a browser feature, and not part of the WebView API. You can set Chrome Canary to be the default browser, so you won't have to uninstall Stable. Go to:

Settings > Apps & notifications > Advanced > Default Apps > Browser app

and select Chrome Canary. Make sure to close and re-start the app so it runs on Canary on the next start.

**Comment by FluorescentHallucinogen** [comment]
@andreban Thanks!
