### ISSUE TITLE
Update TWA Cookies

### ISSUE THREAD

**Issue by BramYeh** [GoogleChromeLabs/svgomg-twa#3]
Since TWA supports first party website, is any possible solution that we can update/sync cookies between TWA and Native parts?

Thanks very much!

**Comment by andreban** [comment]
Hi BramYeh, 

It isn't currently possible to update/sync cookies between TWA and Native parts. The best way to exchange information between both is through Intents.

**Comment by BramYeh** [comment]
@andreban 
Thanks for your information.
