### ISSUE TITLE
Splash Screen Icon?

### ISSUE THREAD

**Issue by SvenBudak** [GoogleChromeLabs/svgomg-twa#30]
Hi @andreban 

Thanks for the Update with Splash Screen Support :) But... can you maybe also add a option that allow people to add a Splash Screen Icon?

```
def twaManifest = [
    applicationId: 'org.chromium.twa.svgomg',
    hostName: 'svgomg.firebaseapp.com', // The domain being opened in the TWA.
    launchUrl: '/', // The start path for the TWA. Must be relative to the domain.
    name: 'SVGOMG TWA', // The name shown on the Android Launcher.
    themeColor: '#303F9F', // The color used for the status bar.
    backgroundColor: '#ffffff' // The color used for the splash screen background.
]
```

Currently is it not possible. I was just wondering why i just see a white Screen when i started the App first time...

**Comment by andreban** [comment]
Have you generated a new splash image for each resolution? Below is the list of files and the resolution used for each image: 

- res/drawable-hdpi/splash.png - 450 x 450px
- res/drawable-mdp/splash.png - 300 x 300px
- res/drawable-xhdpi/splash.png - 600 x 600px
- res/drawable-xxhdpi/splash.png - 900 x 900px
- res/drawable-xxxhdpi/splash.png - 1200 x 1200px

**Comment by SvenBudak** [comment]
Hmm no i dont, but there was still the default images placed.
But they also was not displayed by loading the TWA.

My Second Question: I right clicked on the res folder and generate new img assets. why the splash screens was not also generated?

**Comment by andreban** [comment]
Can you confirm if you are seeing the splash screen?

If you are and you have replaced the icons inside the res/ folder, make sure to rebuild the APK and redeploy the new version, and that should be enough to make it work.

Could you explain more about the second questions? I don't think I understood it.

**Comment by SvenBudak** [comment]
I see only a white screen when i start the App. I already rebuild and clean all project data before i did that. But still no Splash Screen.

To my Second Question:
![1_gTpOQWO2q8PL74KVEzQvYA](https://user-images.githubusercontent.com/4930169/58800591-92aa3780-8608-11e9-8e63-85b4bd5f542b.png)
I did this to generated the App Icons, but this dosnt generated the Splash Icons. So how i create them in a correct way? Manually in Photoshop or something like that?

**Comment by andreban** [comment]
Yes, using something like photoshop and generating manually is the best way. Save them as .pngs and place on the folders mentioned above. Are you using Chrome 75 or above (currently Beta or Canary)?

**Comment by SvenBudak** [comment]
We tested on Version 74.0.3729.169. is it not available until 75? if this is the case, this will explain our problem.

**Comment by andreban** [comment]
Yes, that's correct. It only works on 75 and up.

**Comment by SvenBudak** [comment]
Oh okay... Thanks :) you want maybe to edit the readme or leave a comment in the config array to let people know how they edit the splash icon?

**Comment by SvenBudak** [comment]
Oh okay... Thanks :) you want maybe to edit the readme or leave a comment in the config array to let people know how they edit the splash icon?

**Comment by SvenBudak** [comment]
For some reason in germany we still have chrome 74. when 75 is out i will test this. Thanks for the informations! One small ohter question because i cant find anything at google about this... Is it possible to pass variables from the TWA container into the PWA web app? Like `currentLanguage` or something like that?

**Comment by andreban** [comment]
You can use query parameters or custom headers to pass information when opening the TWA. Does this help?

**Comment by SvenBudak** [comment]
Because this TWA wrapper is the first time i come in contact with Android Studio and real Java Code, i have some problems to follow oyu. can you give me maybe a very short and simple example how to pass a variable from the TWA Wrapper to the PWA?

**Comment by andreban** [comment]
Hi @SvenBudak, 

The solution would be to create your own LauncherActivity by extending the [LauncherActivity in the Support Library](https://github.com/GoogleChrome/custom-tabs-client/blob/master/customtabs/src/android/support/customtabs/trusted/LauncherActivity.java). 

Then, override the [getLaunchingUrl](https://github.com/GoogleChrome/custom-tabs-client/blob/master/customtabs/src/android/support/customtabs/trusted/LauncherActivity.java#L216-L231) method to pass any parameters you want as query parameters.

**Comment by SvenBudak** [comment]
Thanks for this! This will help me. Is anything planned to make it possible to pass an config array or object to the twa?

**Comment by arryanggaputra** [comment]
Thanks, @SvenBudak, themeColor seems not to work at all, I tried to change the color but it still black, do you have any idea about this?

**Comment by happylolonly** [comment]
could someone explain to Android noob (me) how I can replace splash screens by generating (in android studio or something else), not by hands?

**Comment by SvenBudak** [comment]
@happylolonly Read my Tutorial: https://medium.com/@svenbudak/this-twa-stuff-rocks-finally-i-got-my-pwa-on-google-play-store-b92fe8dae31f

**Comment by andreban** [comment]
@happylolonly You may want to take a look at https://github.com/GoogleChromeLabs/llama-pack

It should be able to use your WebManifest to generate both the app icon and the splash screen.

**Comment by andreban** [comment]
Closing this issue, as llama-pack solves this

**Comment by SvenBudak** [comment]
@andreban is there somewhere a tutorial how Ilama-pack is to use? its a package that we should use additional to SVGOMG-TWA ? or we dont need SVGOMG-TWA any more?

**Comment by andreban** [comment]
The [README file](https://github.com/GoogleChromeLabs/llama-pack/blob/master/packages/cli/README.md) on the [llama-pack](https://github.com/GoogleChromeLabs/llama-pack) repository should have the details you need. Please, file a bug against llama-pack if there's something missing or unclear.
