### ISSUE TITLE
Please add Options for Fallback to Website if TWA is not Supported

### ISSUE THREAD

**Issue by SvenBudak** [GoogleChromeLabs/svgomg-twa#31]
Hi @andreban, sorry but i have another feature request to you ;)

I got my TWA: https://play.google.com/store/apps/details?id=com.devMonkeys.expenser i got alot feedback (Also one bad rating) because people can download the App with devices they dont support TWA...

my please to you: Can you check please a possibility to add 2 Options?

1. Boolean that set the dependencylist correctly, that it shows the App in Playstore only if peoples device support TWA

2. Open a Dialog inside the App, when it runs on a Device that have no TWA Support, with text: `Your device is not supporting TWA, you want to open the App in your Browser?` and if they click yes it just opens the URL of the PWA inside Chrome.

I know it makes no sense to use both at same time, but maybe some people want to list it in store for marketing reasons, so thy set `1.` to false and use `2.` to catch customers. Also this will help to make TWA more popular.

**Comment by andreban** [comment]
Hi @SvenBudak 

It'd be great if you could raise both issues on https://bugs.chromium.org/. That's where we track bugs and feature requests for TWA and the TWA Support Library.

Andre

**Comment by SvenBudak** [comment]
Thanks I will take a look. But isn't this a thing that must be made in this repository? In gradle.build file?

**Comment by andreban** [comment]
The code that checks if the TWA is available is part of the Support Library. The best place to file bugs for the Support Library is on the Chromium repository.

**Comment by SvenBudak** [comment]
But i talk about hiding the app in the playstore... The playstore is a native app i think, and the wrapper is also a native java app. i want to hide the TWA App Container in the PlayStore if the user dont have Chrome 75+ installed...

I think you talk about a solution to show something if he have allready downlaoded the TWA from palystore and start the app, and his chrome is not supporting TWA feature...
