### ISSUE TITLE
Handle back button in TWA

### ISSUE THREAD

**Issue by mathcoll** [GoogleChromeLabs/svgomg-twa#32]
Hi,

I'm not sure I should post this request here.. But I have set a PWA+TWA using this repo to start.
I managed to get the expected result, except on the mobile "back" button which seems not to works as expectd on the TWA.

Actually, when I tap to back button on my mobile, nothing is happening. and the PWA (so the TWA) is using "window.location.hash" to handle the pages changes.

Is there anything I can do so far?

Thanks.

**Comment by rockeynebhwani** [comment]
@mathcoll  - Is this duplicate of https://github.com/GoogleChromeLabs/svgomg-twa/issues/57 ?

**Comment by mathcoll** [comment]
Hi,
This issue #32 is more a feature request and #57 seems a bug.
Well, I can't say #57 is a duplicate. Maybe it is related as both issues are talking about back buttons.

So if I could rephrase this issue: 
I'd like to control the TWA previous-page from history by using the Mobile back button.

**Comment by PEConn** [comment]
@andreban You're a bit more knowledgable about HTML back behaviour, could you have a look at this?

@mathcoll If you navigate to your web page in normal Chrome, does the back button work as intended?

**Comment by mathcoll** [comment]
> in normal Chrome, does the back button work as intended?
Well ..
Seems it doesn't works (anymore ??) I believe it was working but I'm not even sure now ...
So, it seems there is at least a bug in **my code** handling the window.location.hash. We probably can close this issue and if I can fix my issue first, I'll reopen the tikcket.
