### ISSUE TITLE
Is it possible to monetize a pwa through twa?

### ISSUE THREAD

**Issue by genesy** [GoogleChromeLabs/svgomg-twa#37]
I'm not an android developer by any means so i'm not exactly sure how this repository works. But is it possible to add admob or something for the app?

**Comment by andreban** [comment]
Would you mind posting this question on StackOverflow, as this is a question about TWAs in general and not an issue with the sample in this repo? We have a specific tag for TWAs at https://stackoverflow.com/questions/tagged/trusted-web-activity/
