### ISSUE TITLE
Digital Asset Links dont work?

### ISSUE THREAD

**Issue by BamiGorengo** [GoogleChromeLabs/svgomg-twa#4]
I read this Docu: https://developers.google.com/web/updates/2019/02/using-twa#remove_the_url_bar

So i created: https://ausgaben-rechner.firebaseapp.com/.well-known/assetlinks.json

And edit the `manifestPlaceholders` in https://github.com/GoogleChromeLabs/svgomg-twa/blob/master/app/build.gradle#L38

But after build i still see the URL Bar... Is there maybe any bug?

**Comment by andreban** [comment]
There are a few places where the configuration may be wrong, and it's hard to diagnose without looking at the files. Can you please double-check:

- If the package name on https://ausgaben-rechner.firebaseapp.com/.well-known/assetlinks.json matches the package name from your app.
- If the SHA-256 Fingerprint matches your keystore fingerpring.
- If the URL in asset_statements matches the URL in your file.
- If the URL being opened matches the domain inside asset_statements.

**Comment by BamiGorengo** [comment]
Sorry that i dont include directly a Repository link in my first post: https://github.com/BamiGorengo/ExpenseCalculatorTWA

I think i did everything correctly.

**Comment by andreban** [comment]
Source code looks ok. Is the app published on the Play Store? I can try installing and checking the signatures.

**Comment by BamiGorengo** [comment]
yeah it is, it a closed test. When you give me your gmail address, then i can add you to the testers list.

**Comment by andreban** [comment]
Same as my Github username :)

**Comment by BamiGorengo** [comment]
Thanks :)

https://play.google.com/apps/internaltest/4698262063010324100

**Comment by BamiGorengo** [comment]
Die you do some changes? The URL bar is gone. This is really strange. Because i do nothing science yesterday. Is it possible that this stuff simply needs some time to get aplyed?

**Comment by andreban** [comment]
Nothing changed. 

One possible cause is the version of the Support Library being used. The version in the demo had an issue that showed the URL Bar when the TWA is opened and Chrome is being cold-started. Updating the Support Library version fixes the issue:

```
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.github.GoogleChrome.custom-tabs-client:customtabs:7ab7178ae0'
}
```

**Comment by tirthbodawala** [comment]
I am facing a similar issue with below dependencies:
```
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.github.GoogleChrome:custom-tabs-client:e446d08014'
}
```
Apologies, I am nood with android development. I used the tool https://appmaker.xyz/pwa-to-apk/ and it shows me the url bar.

**Comment by andreban** [comment]
@tirthbodawala Is `.well-known/assetlinks.json` acessible from your domain? I think the tool provides the relevant file to upload to this location. Can you check if the content-type is `application/json`?

**Comment by tirthbodawala** [comment]
@andreban there was an error in rendering `.well-known/assetlinks.json` I have corrected it at 
https://hn.reactpwa.com/.well-known/assetlinks.json 
Do I need to update the app or do anything further?

**Comment by andreban** [comment]
@tirthbodawala, if the tool generated everything correctly yes. Btw, since this is not related to the SVGOMG demo, http://stackoverflow.com/questions/tagged/trusted-web-activity/ is a good place to post the question.

**Comment by andreban** [comment]
Closing the issue as the original question was an answered and solved.

**Comment by egemon** [comment]
Hi guys! Had the same problem. 
Wanna let u know that in my case issue was that previous assetlinks.json file was CACHED in default browser (chrome in my case).
So verification were always failing and this depends on server which serves static.
So u have to go to website with the same browser and just clear cache to apply changes.
Hope this will help smbd.

**Comment by GF-** [comment]
Hi all,
a heads up: if Firefox is set as a default browser on the Android settings of your device, then the address bar will show up regardless.
In my case assetlinks and signatures were all configured correctly, but the address bar went away once I actually set Chrome as default browser.

I hope that helps.

**Comment by AlexBorsody** [comment]
If someone is technical enough to be able to/want to do that, they will probably understand what PWAs are and not be bothered by it or even think it's cool.

There is a long way to go regarding this stuff though, sharing state with the browser is another big gotcha.
