### ISSUE TITLE
Run twa in fullscreen mode without Action- and Statusbar 

### ISSUE THREAD

**Issue by fabianbormann** [GoogleChromeLabs/svgomg-twa#40]
Hi there,

we are building a pwa game and want to launch it also as twa without action- and statusbar in fullscreen mode. Currently I found no way to do this and my received answer on [stackoverflow](https://stackoverflow.com/questions/55662370/hide-statusbar-in-trusted-web-activities) does not work me. So (how) is it possible to run a twa completely without ui (actionbar, statusbar) in fullscreen mode?

Thanks! 😊

**Comment by andreban** [comment]
Hi Fabian,

Thanks for reaching out. Immersive mode is not currently supported. We do have a [feature request open in the Chromium bugtracker](https://bugs.chromium.org/p/chromium/issues/detail?id=965329&q=component%3AUI>Browser>Mobile>TrustedWebActivities%20immersive&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified). It would be great if you could chime in there too.

Andre

**Comment by fabianbormann** [comment]
Hi Andre,

thanks for your fast reply 

> It would be great if you could chime in there too

will definitely do that 👍 

In this case I would close this issue here. Thanks a lot! 😊

**Comment by mshamaseen** [comment]
any updates here?
