### ISSUE TITLE
Not able to put a svg gradient as TWA splash screen background.

### ISSUE THREAD

**Issue by momoproject** [GoogleChromeLabs/svgomg-twa#44]
I'm not sure if this is even possible, but is there some way to do it?

```
<meta-data
android:name="android.support.customtabs.trusted.SPLASH_SCREEN_BACKGROUND_COLOR"
android:resource="@color/backgroundColor"/>
```
Being, `@drawable/gradient` instead of `@color/backgroundColor`, I did this but didn't worked, the app just throws an error, I asked this on Stack too, but didn't got an answer, so I thought on asking here, it would be good as an enhacement.

![image](https://user-images.githubusercontent.com/40412640/64362258-945b1100-cfe4-11e9-87c6-3cc19282508d.png)

**Comment by andreban** [comment]
Created this [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1054736) on bugs.chromium.org to track this as a feature request. 
Closing the issue here in favour of that one.
