### ISSUE TITLE
I want to hide a div in twa app

### ISSUE THREAD

**Issue by bsde1234** [GoogleChromeLabs/svgomg-twa#45]
I used below code to hide a div in twa, but not working,

```
<script>
if (window.matchMedia('(display-mode: standalone)').matches) {
  console.log('display-mode is standalone');
  document.getElementById("play-button").style.display = 'none';
}
</script>
```
How to do it?

**Comment by mathcoll** [comment]
I believe you can use a regexp to identify when "pageReferrer" match "android-app://"

**Comment by bsde1234** [comment]
can you please give full code, not a coder here

**Comment by mathcoll** [comment]
@bsde1234 I'm not a coder too.
I used Google Tag Manager to do so:
<a href="http://i.imgur.com/shnYeVA.png">
  <img src="http://imgur.com/shnYeVAl.png" />
</a>

But I guess something similar to that could works:
```
if ( document.referrer.match("android-app://") ) {
  alert("Displaying inside the TWA");
} else {
  alert("Please install the App from Google Play");
  document.getElementById("myDiv").display = "block";
}
Please try and let us know.
```

**Comment by bsde1234** [comment]
Thanks, that worked.

**Comment by bsde1234** [comment]
Any javascript code to differentiate between android browser and in-app browser that can be inserted/used in website? Can I use the same tag manager? Please explain.

**Comment by andreban** [comment]
This is beyond the scope of this sample. Would you mind asking this question on http://stackoverflow.com/? The chance of getting help from people who fully understand GTM is way higher.

**Comment by bsde1234** [comment]
@andreban already posted there, please check it.

**Comment by bsde1234** [comment]
Hi,
I have asked a question in https://stackoverflow.com/questions/61517599/hide-div-in-a-custom-tab-opened-from-a-trusted-web-activity 
Let me explain a littile bit more.

My twa website is https://www.monsoonmalabar.com/
In the above site there is a link to external site which is https://keralapsc.monsoonmalabar.com/ when clicking this link in twa app, this link openes in in-app browser. In that in-app browser(website: https://keralapsc.monsoonmalabar.com) there is a button floats left side with link `https://play.google.com/store/apps/details?id=com.monsoonmalabar.app`. I want to hide that link(button) when user using twa(in-app browser). According to your suggestion in the stackoverflow site, I added the external link as https://keralapsc.monsoonmalabar.com/?hideDiv=true  
And added a code in external site as  
```
<script>
  var url_string = window.location.href; //window.location.href
var url = new URL(url_string);
if(url.searchParams.get("hideDiv")) {
  document.write('<div></div>');
} else {
  document.write('<div id="play_button"><a class="btn_openinapp" data-attr="btn_openinapp" href="https://play.google.com/store/apps/details?id=com.monsoonmalabar.app" style="left: 0px;">ആപ്പിൽ തുറക്കുക</a></div>');
}

</script>
```

Now what happenes is during the first visit from twa(wich have hideDive=true) the button disappears. But when I continue to surf external site by going to another page in that external site button shows again. May be I didn't understand you correctly. Can you please explain a little bit more with codes. I am new to coding. My twa app is https://play.google.com/store/apps/details?id=com.monsoonmalabar.app

Thanks.
