### ISSUE TITLE
[Ask] How to use Google Play App Signing in Debug 

### ISSUE THREAD

**Issue by thanhtungka91** [GoogleChromeLabs/svgomg-twa#47]
1. I have done to app signing on google play console. 
2. get SHA-256 certificate fingerprin from App signing 
3. Add SHA-256 certificate fingerprin on ssetlinks.json to PWA site. 
=> downloading the app from google play, the address bar is hidden when running the app, because app sign is meet between the website and app. 

There is a problem in here that if I want to build an APK file in Android studio the key signing which is upload certificate (gen from keystore, not app signing from) so TWA app will show the address bar? 
I would like to know how to use google app sign if I want to build an APK file at the local?

**Comment by andreban** [comment]
When using App Signing, Google Play will not provide you with the certificate used to sign the final APK, so you won't be able to use it for debugging. 

One alternative would be to modify your assetstatements.json file to contain both the fingerprint used by the Play Store and the one for your debug key.

The `sha256_cert_fingerprints` is an array and you could do something like used [here](https://svgomg.firebaseapp.com/.well-known/assetlinks.json).

**Comment by thanhtungka91** [comment]
@andreban  it works, thanks

**Comment by andreban** [comment]
Great to hear that! Maybe it's worth asking / replying on StackOverflow, as it would help others with the same questions to find it. We have a [tag](https://stackoverflow.com/questions/tagged/trusted-web-activity/) for TWAs. Let me know if you'd like to post the question and answer.

**Comment by thanhtungka91** [comment]
@andreban yep, it is very helpful if we can post this question to StackOverflow. 
thanks.

**Comment by melvas6** [comment]
> When using App Signing, Google Play will not provide you with the certificate used to sign the final APK, so you won't be able to use it for debugging.
> 
> One alternative would be to modify your assetstatements.json file to contain both the fingerprint used by the Play Store and the one for your debug key.
> 
> The `sha256_cert_fingerprints` is an array and you could do something like used [here](https://svgomg.firebaseapp.com/.well-known/assetlinks.json).

Hi,
Is it possible to post the solution here? The website link is down. 
Should I just use both keys in  `sha256_cert_fingerprints` or make another relation object as in linking for multiple apps?

**Comment by PEConn** [comment]
You should make multiple relation objects, for example my assetlinks.json file is:

```
[{
  "relation": ["delegate_permission/common.handle_all_urls"],
  "target": {
    "namespace": "android_app",
    "package_name": "dev.conn.drink",
    "sha256_cert_fingerprints": [
      "8C:18:7D:26:05:EE:2E:AF:4B:76:20:6F:39:7B:04:13:91:A2:E2:EC:C4:43:04:E1:25:E8:B8:E0:F4:73:5F:80"
    ]
  }
},
{
  "relation": ["delegate_permission/common.handle_all_urls"],
  "target": {
    "namespace": "android_app",
    "package_name": "dev.conn.drink",
    "sha256_cert_fingerprints": [
      "73:9E:C8:99:79:F1:A3:7F:12:95:54:D8:A5:8E:BB:8B:BB:52:76:15:F8:FC:CB:10:D5:E4:44:89:BD:4B:8E:3A"
    ]
  }
},
{
  "relation": ["delegate_permission/common.handle_all_urls"],
  "target": {
    "namespace": "android_app",
    "package_name": "dev.conn.drink",
    "sha256_cert_fingerprints": [
      "3B:C3:C4:34:CB:E5:96:62:FF:D7:3B:19:65:64:1A:E3:AF:DF:67:FE:E9:43:34:22:DE:72:E9:BE:D9:26:DA:3A"
    ]
  }
}]
```

**Comment by melvas6** [comment]
@PEConn 
Thanks a lot for the quick response. It is working.
