### ISSUE TITLE
Status Bar Color Precedence Issue

### ISSUE THREAD

**Issue by strygo** [GoogleChromeLabs/svgomg-twa#49]
I'm seeing an issue with the status bar color, and I'm not sure whether the problem is in this test app, the support library, Chrome, or something I'm doing wrong.

https://bugs.chromium.org/p/chromium/issues/detail?id=964914

According to that issue, if a trusted webpage specifies a theme color, this theme color should take precedence over any values specified in the app.

However, I'm not seeing this behavior with the test app. To test this, I've done the following:

1. Navigate to https://svgomg.firebaseapp.com/ and install the app to the home screen.
2. Observe that the status bar is a dark blue color (#303F9F)
3. Update the TWA's twaManifest.themeColor to #00FFFF
4. Run the app and observe the color is turquoise rather than dark blue

It looks like this change should have landed in Chrome 76, but I'm not seeing it in Chrome 77.

Am I missing something obvious?

**Comment by PEConn** [comment]
Hey Steve,

I'm assuming that the page is in Custom Tab mode, not TWA mode (there's a
top bar)? The web page's theme colour is only used when you're on the
verified origin (you're in TWA mode), once you leave and you're on a Custom
Tab the theme colour specified in the manifest applies.

Basically, we want to give the Android App developer control over the
topbar/status bar colour. When you're on a website that you can prove that
you own (the verified origin), we pay attention to the theme colour if it's
present. When you're on a 3rd party website we believe that the theme
colour that the Android App developer specified should take precedence over
the theme colour of the website. This way the Android App can have a
consistent theme overall.

Peter

**Comment by strygo** [comment]
Hi Peter,

Thank you for the thorough reply. This behavior you describe makes sense, and what I would expect to see.

Using the sample app, and following the steps documented [here](https://developers.google.com/web/updates/2019/02/using-twa#debugging), I added the sample's app's domain. Upon doing this, the app appears to run in TWA mode (the address bar isn't shown). I also see a "You are using an unsupported feature flag: CommandLineOnNonRooted. Stability and security will suffer." Is it possible it still isn't fully in TWA mode?

Because I thought this might be the case, I tried loading a fully signed version of my app (which derives from the sample). When I do that, the address bar also isn't shown, but the status bar still doesn't behave how I would expect.

In my app, I did discover a behavior that may help identify the source of the issue.

1. Launch app into TWA mode (no address bar shown) - Status Bar: taken from STATUS_BAR_COLOR meta-data (INCORRECT)
2. Navigate to a different domain (address bar shown) - Status Bar + Top Bar: taken from STATUS_BAR_COLOR meta-data (CORRECT)
3. Navigate back to TWA page (no address bar shown) - Status Bar: taken from meta theme-color tag (CORRECT)

So it seems that there might be an issue with initialization. Any other ideas on your end? Thanks for your help.

Steve

**Comment by PEConn** [comment]
This sounds like this is a problem our (Chrome's) end. I don't think the "unsupported feature flag" warning should be effecting this.

Can I get the full version of Chrome you're using?

**Comment by strygo** [comment]
Sure. It's 77.0.3865.92. If you need any other info from me, please let me know.

**Comment by PEConn** [comment]
I can reproduce this issue on Chrome Stable, however it's working as expected on Chrome Canary - I believe it was fixed with https://chromium-review.googlesource.com/c/chromium/src/+/1771316 .

**Comment by strygo** [comment]
I've confirmed I'm seeing the correct behavior with Chrome Canary installed as well. Thanks for the help!

**Comment by PEConn** [comment]
Great! The fix should be in Chrome 79, which should get to Chrome Beta on mid October and to Stable in mid December.
