### ISSUE TITLE
Is there way to launch APP in fullscreen UI with no browser controls ?

### ISSUE THREAD

**Issue by amituidev** [GoogleChromeLabs/svgomg-twa#5]
Hi, 

Is there way to launch the app in fullscreen without browser control options.
Currently its looking like this ->

![](https://i.ibb.co/JyGBQTx/Screenshot-2019-02-12-15-51-27-118-com-chrome-canary.png)

**Comment by BamiGorengo** [comment]
Take a look on my issue :)

https://github.com/GoogleChromeLabs/svgomg-twa/issues/4

**Comment by amituidev** [comment]
Thank you @BamiGorengo

**Comment by andreban** [comment]
Duplicate of #4
