### ISSUE TITLE
How to support multi environment urls?

### ISSUE THREAD

**Issue by magbicaleman** [GoogleChromeLabs/svgomg-twa#52]
I'm very new to `Android Studio` and `android` development as a whole. I found this article to work [twas-quickstart](https://developers.google.com/web/updates/2019/08/twas-quickstart), but not so much this article: [using-twa](https://developers.google.com/web/updates/2019/02/using-twa)

What's the way to change the hostname and release it to a particular track in the Google Play Store?

I released our first ever version of the TWA to the **Internal Track** in the Play Store pointing to a `beta` URL just to test it out. 

If I want to change my `hostName` in the `build.gradle` do I change that value, build and then upload that `app bundle` to a different release track, e.g, production track? 

I'm aware that I need to probably have two `sha256_cert_fingerprints` in my assetlinks.json, that's taken care of.

**Comment by andreban** [comment]
@magbicaleman 

Yes, changing the `hostName` in `build.gradle` is the way to go if you want to change the origin the TWA opens.

Deploying different bundles to different tracks should work. The usual way to work with alpha, beta, and production tracks is that builds are "promoted" from one track to the other, but this won't work as intended in this case, as promoting a beta track to production would take users in production to open the beta URL.

Is there a reason why you want to sync beta versions of the Android build to beta version of the website? If they are not connected at all, you may want to consider using traditional A/B testing tools for the website and have a single build of the TWA.

**Comment by magbicaleman** [comment]
@andreban thank you very much for your feedback.

> Is there a reason why you want to sync beta versions of the Android build to beta version of the website

This is just the setup we currently have if we wanted to post data that we don't want to show in a production environment.

>  If they are not connected at all
What do you mean by this?

Do you have recommendations or resources on better handling deployments? I'd like to get better at this.

**Comment by andreban** [comment]
[Play documentation](https://support.google.com/googleplay/android-developer/answer/3131213?hl=en-GB) would be the best place to look into deployments.
