### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by konstantin1883** [GoogleChromeLabs/svgomg-twa#57]
When you close the application with the back button, a white blank screen is displayed for a short period of time, how can I fix this?

**Comment by PEConn** [comment]
Thanks for this bug report and very sorry for taking so long to get back to you on it. We're tracking this bug at https://crbug.com/1026226 .

**Comment by andreban** [comment]
Closing the bug here, in favor of tracking at crbug. We can re-open if a change in the SVGOMG App is required.
