### ISSUE TITLE
Fullscreen mode exists in PWA but not TWA?

### ISSUE THREAD

**Issue by n-belokopytov** [GoogleChromeLabs/svgomg-twa#58]
It seems quite weird to us that Status and Nav bar cannot be hidden in TWA activity even though it's a non-issue for a PWA installed app. Can anything be done about it?

**Comment by andreban** [comment]
This is being looked into and tracked in this Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=965329

We're going to add this to the sample, once Chrome supports it.

**Comment by happylolonly** [comment]
guys, you mean status bar or navigation one?

I installed my app from .apk file, it had only status bar.
Then I deployed it to Play Store, but it have status bar and navigation...

I uploaded `assetlinks.json` to website.

**Comment by andreban** [comment]
@happylolonly we mean the status bar

re: Navigation bar when downloading from Play, you may have the wrong Fingerprint in the assetlinks.json, if you enabled App Signing on Play (which is the default). You can install [Peter's Asset Link Tool](https://play.google.com/store/apps/details?id=dev.conn.assetlinkstool) and use it to check for the correct assetlinks.json file.

**Comment by PEConn** [comment]
I think you may have verified your app with your debug key, not your production key. Have a look at https://developers.google.com/web/updates/2019/08/twas-quickstart#a-note-on-signing-keys

**Comment by happylolonly** [comment]
thanks, I changed SHA in `assetlinks.json`, now without navigation;)

**Comment by andreban** [comment]
Closing the issue here, in favour of tracking in Chromium Bugs: https://bugs.chromium.org/p/chromium/issues/detail?id=965329

**Comment by mshamaseen** [comment]
Is there any way on the earth to do this?

**Comment by andreban** [comment]
https://stackoverflow.com/questions/62797222/how-to-make-android-app-using-twa-full-screen-immersive
