### ISSUE TITLE
[Proposal] Use web app manifest as single source of truth

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [GoogleChromeLabs/svgomg-twa#59]
Currently, developers when packaging PWA to TWA should duplicate web app manifest properties in [build.gradle](https://github.com/GoogleChromeLabs/svgomg-twa/blob/master/app/build.gradle#L21) file, that has a different format.

What about using `manifest.webmanifest` file as single source of truth and generate `build.gradle` from it? This should improve the DX (Developer Experience).

**Comment by andreban** [comment]
This is something we considered previously. The bottom line was that the fields cannot be used straight from the Web Manifest, and use the same format.

As an example, while a Web Manifest accepts `red` or `blue` to specify a `background_color`, Android will require the color to be specified as `#FF0000` or `#0000FF`.

Having said that, we are looking into how we can generate an Android Project from a Web Manifest, without having to mess around with `build.gradle`. I'll update this issue when this moves forward.

**Comment by FluorescentHallucinogen** [comment]
@andreban Just found https://github.com/GoogleChromeLabs/llama-pack. ;)

**Comment by andreban** [comment]
That's the project I mentioned above. It's a work in progress, but it is public now. Issues and PRs are welcome!

**Comment by andreban** [comment]
I created an issue on llama-pack to discuss this: https://github.com/GoogleChromeLabs/llama-pack/issues/11

**Comment by FluorescentHallucinogen** [comment]
:tada:
