### ISSUE TITLE
Transparent statusbar possible?

### ISSUE THREAD

**Issue by kalkih** [GoogleChromeLabs/svgomg-twa#63]
Hello!
I've got a web app where the theme is heavily based around the currently viewed content.
Is it possible to make the status bar translucent or transparent?

If that isn't possible, how would I best go about changing the status bar color dynamically based page content?

In a normal browser window and as a PWA I can achieve this by changing the content of the meta tag `theme-color`.

Thanks!

**Comment by PEConn** [comment]
We're working on adding support for Android's Immersive Mode which I think would solve your problem - we're tracking this on the android-browser-helper library: https://github.com/GoogleChrome/android-browser-helper/issues/35

(the android-browser-helper library will soon be replacing the custom-tabs-client library that svgomg-twa is based on)

**Comment by kalkih** [comment]
Great, thanks for your response!
