### ISSUE TITLE
Create default values for the the app`build.gradle` TWA configuration

### ISSUE THREAD

**Issue by andreban** [GoogleChromeLabs/svgomg-twa#64]
Currently, all configurations are specified on the top of the application's `build.gradle`. Values like  `enableNotifications`, `useBrowserOnChromeOS` and `shortcuts` are not frequently used and, as more configurations are added, the configuration ends up with a lot of visual pollution, making it harder for developers to understand.

For the values that can have defaults specified, those should be specified in the build script, and should only be added to the configuration section if a developer wants to override the default value.

This will make the configuration section shorter and easier understand.

@PEConn, WDYT?

**Comment by PEConn** [comment]
On the other hand, I think that the relevant part of the config file still fits onto a page (it's only 20 lines now) and it acts as a nice way to advertise TWA features. I could see a developer going to `build.gradle` to enter their host name and theme colour, spotting the shortcuts entry and trying it out.

If the `twaManifest` structure doubles or triples in size, I'd agree that we need to cut it down, but for now I think it's a nice place to find all the levers a developer can play around with.

**Comment by andreban** [comment]
Fair enough. I'll re-raise this if this becomes an issue in the future.
