### ISSUE TITLE
Show notifications in shortcuts

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [GoogleChromeLabs/svgomg-twa#66]
How to show notifications in shortcuts? Something like this:

![shortcut-notifications](https://user-images.githubusercontent.com/7892779/68765905-efd1fc80-062e-11ea-981c-8212430fc26d.png)

**Comment by FluorescentHallucinogen** [comment]
Is enabling the notification delegation enough to display icon dots and notifications in shortcuts?

**Comment by FluorescentHallucinogen** [comment]
@andreban @PEConn cc.

**Comment by PEConn** [comment]
Hey,

Admittedly I haven't tried this myself, but from reading [here](https://developer.android.com/training/notify-user/badges) they "appear on a launcher icon when the associated app has an active notification" and "These dots appear by default in launcher apps that support them and there's nothing your app needs to do" so I believe you're right. Once notification delegation is enabled, they should appear.

Peter

**Comment by andreban** [comment]
Closing this, as it seems PEConn's response solves the issue.
