### ISSUE TITLE
Multiple TWAs on same domain?

### ISSUE THREAD

**Issue by leolux** [GoogleChromeLabs/svgomg-twa#70]
Let's assume we have three different PWAs running at the same domain:

- https://myexamplehost.com/pwa1
- https://myexamplehost.com/pwa2
- https://myexamplehost.com/pwa3

1. Is TWA capable of different PWAs on the same domain?
2. How many **assetlinks.json** files are required for the TWA to work correctly?
3. Where to place the **assetlinks.json** file for each PWA?

**Comment by PEConn** [comment]
Hey,

Sorry, do you mind being a bit clearer about what you mean by "Is TWA capable of different PWAs on the same domain"? Do you just want a single TWA to be able to view each of your PWAs, or do you want to be able to create 3 different TWAs, one for each PWA?

While PWAs (things with the web app manifest) can have more specific scopes (eg, https://myexamplehost.com/pwa1), TWAs and Digital Asset Links really only care about origins (eg https://myexamplehost.com/).

If you want to have a single TWA that serves all your PWAs, you would:

1. Create the assetlinks.json file at https://myexamplehost.com/.well-known/assetlinks.json.
2. Add your single TWA to the assetlinks.json.
3. Set up your TWA to launch to whichever PWA you want to first launch to.
4. Create hyperlinks between your PWAs so users can move from one to another.
5. Maybe make use of the `shortcuts` property in `build.gradle` to create a shortcut to each PWA.

If you want to have 3 different TWAs, one for each PWA, you would:

1. Create the assetlinks.json file at https://myexamplehost.com/.well-known/assetlinks.json.
2. Create entries in assetlinks.json for each TWA.
3. Set up each TWA to launch to its corresponding PWA.

Unfortunately in this second case things may get a bit confusing if you use Notification Delegation (essentially Chrome may get confused with which app should show your website's notifications) - but we can cross that bridge if we come to it.

Peter

**Comment by leolux** [comment]
Thank you for the explanation!

I like to have 3 different apps to be published to the google play store, one for each PWA. So I guess that I need 3 different TWA for that. 

I couldn't find a good documentation about assetlinks.json How to create the correct entries in assetlinks.json and where to read on?

**Comment by PEConn** [comment]
You can get some info about making your Digital Asset Links at the [quick start guide here]. [Here](https://peconn.github.io/.well-known/assetlinks.json) is an example of a Digital Asset Link file that contains multiple verified TWAs.

[quick start guide here]: https://developers.google.com/web/updates/2019/08/twas-quickstart#creating-your-asset-link-file

**Comment by andreban** [comment]
The root element on `assetlinks.json` is an array. You can use that to list multiple applications that have access to the domain:

```json
[{
  "relation": ["delegate_permission/common.handle_all_urls"],
  "target": {
    "namespace": "android_app",
    "package_name": "com.mysamplehost.pwa1",
    "sha256_cert_fingerprints": ["<82:04:C5:DB:19:A8:B9...>"]}
},{
  "relation": ["delegate_permission/common.handle_all_urls"],
  "target": {
    "namespace": "android_app",
    "package_name": "com.mysamplehost.pwa2",
    "sha256_cert_fingerprints": ["82:04:C5:DB:19:A8:B9..."]}
},{
  "relation": ["delegate_permission/common.handle_all_urls"],
  "target": {
    "namespace": "android_app",
    "package_name": "com.mysamplehost.pwa3",
    "sha256_cert_fingerprints": ["82:04:C5:DB:19:A8:B9..."]}
}]
```

A few things to note:

1. Each entry has a different package name, which will point to the corresponded TWA
2. You can use the same signing key or different signing keys. If using Play Store signing (recommended), those keys will probably be different.
3. You will want to tweak the [`intent-filter` in the `AndroidManifest.xml`](https://github.com/GoogleChromeLabs/svgomg-twa/blob/master/app/src/main/AndroidManifest.xml#L71-L77) to handle things correctly. They would look something like this:

```xml
 <intent-filter android:autoVerify="true">
     <action android:name="android.intent.action.VIEW"/>
     <category android:name="android.intent.category.DEFAULT" />
     <category android:name="android.intent.category.BROWSABLE"/>
     <data android:scheme="https"
           android:host="myexamplecost.com"
           android:path="/pwa1" />
</intent-filter>
```

**Comment by the-white-tiger** [comment]
@leolux I am working on something similar as you i.e. multiple twa on same domain . I want to know if the above solution worked for you and also how did you manage to enable push notifications in the three TWAs

**Comment by PEConn** [comment]
Push notifications should work with multiple TWAs for the same origins, although the state is a little messy.

Basically, Chrome's permission model is keyed by the origin - so you've got the same notification permission for www.example.com, www.example.com/path and www.example.com/longer/path. For notification delegation auto-enrollment (where Chrome grants your website the notification permission provided your TWA has it), the permission for your entire origin will be the permission for whichever app has the broadest intent filter. However, the notifications themselves have a scope, so they may be routed to your specific TWAs, for example:

* TWA #1 has notification delegation enabled and an intent filter for www.example.com/.
* TWA #2 has notification delegation enabled and an intent filter for www.example.com/path.

The notification permission for www.example.com will be set according to that for TWA #1, however, if you send a notification from www.example.com/path, it will get routed to TWA #2 (which may not have notifications enabled).

(If on the other hand, you used different subdomains, (cats.example.com and dogs.example.com) everything should work and be a lot simpler.)

**Comment by the-white-tiger** [comment]
thanks for help @PEConn . Can you please also check this stackoverflow  [thread](https://stackoverflow.com/questions/63533523/fcm-push-notifications-on-mutliple-twa-on-same-domain) where I have asked my question more elaborately. Thanks

**Comment by jitendra1607** [comment]
@andreban @PEConn 
How to generate 'assetslinks.json' dynamically if i have thousands of PWA (pwa1, pwa2 .... so on). Can I add query param or path variable to the request(initiated from android for verification) decide the respective 'assetslinks.json' to be served from server?

**Comment by Mohit-Hasan** [comment]
> The root element on `assetlinks.json` is an array. You can use that to list multiple applications that have access to the domain:
> 
> ```json
> [{
>   "relation": ["delegate_permission/common.handle_all_urls"],
>   "target": {
>     "namespace": "android_app",
>     "package_name": "com.mysamplehost.pwa1",
>     "sha256_cert_fingerprints": ["<82:04:C5:DB:19:A8:B9...>"]}
> },{
>   "relation": ["delegate_permission/common.handle_all_urls"],
>   "target": {
>     "namespace": "android_app",
>     "package_name": "com.mysamplehost.pwa2",
>     "sha256_cert_fingerprints": ["82:04:C5:DB:19:A8:B9..."]}
> },{
>   "relation": ["delegate_permission/common.handle_all_urls"],
>   "target": {
>     "namespace": "android_app",
>     "package_name": "com.mysamplehost.pwa3",
>     "sha256_cert_fingerprints": ["82:04:C5:DB:19:A8:B9..."]}
> }]
> ```
> 
> A few things to note:
> 
> 1. Each entry has a different package name, which will point to the corresponded TWA
> 2. You can use the same signing key or different signing keys. If using Play Store signing (recommended), those keys will probably be different.
> 3. You will want to tweak the [`intent-filter` in the `AndroidManifest.xml`](https://github.com/GoogleChromeLabs/svgomg-twa/blob/master/app/src/main/AndroidManifest.xml#L71-L77) to handle things correctly. They would look something like this:
> 
> ```
>  <intent-filter android:autoVerify="true">
>      <action android:name="android.intent.action.VIEW"/>
>      <category android:name="android.intent.category.DEFAULT" />
>      <category android:name="android.intent.category.BROWSABLE"/>
>      <data android:scheme="https"
>            android:host="myexamplecost.com"
>            android:path="/pwa1" />
> </intent-filter>
> `Great ! working fine

**Comment by jitendra1607** [comment]
> > The root element on `assetlinks.json` is an array. You can use that to list multiple applications that have access to the domain:
> > ```json
> > [{
> >   "relation": ["delegate_permission/common.handle_all_urls"],
> >   "target": {
> >     "namespace": "android_app",
> >     "package_name": "com.mysamplehost.pwa1",
> >     "sha256_cert_fingerprints": ["<82:04:C5:DB:19:A8:B9...>"]}
> > },{
> >   "relation": ["delegate_permission/common.handle_all_urls"],
> >   "target": {
> >     "namespace": "android_app",
> >     "package_name": "com.mysamplehost.pwa2",
> >     "sha256_cert_fingerprints": ["82:04:C5:DB:19:A8:B9..."]}
> > },{
> >   "relation": ["delegate_permission/common.handle_all_urls"],
> >   "target": {
> >     "namespace": "android_app",
> >     "package_name": "com.mysamplehost.pwa3",
> >     "sha256_cert_fingerprints": ["82:04:C5:DB:19:A8:B9..."]}
> > }]
> > ```
> > 
> > 
> > A few things to note:
> > 
> > 1. Each entry has a different package name, which will point to the corresponded TWA
> > 2. You can use the same signing key or different signing keys. If using Play Store signing (recommended), those keys will probably be different.
> > 3. You will want to tweak the [`intent-filter` in the `AndroidManifest.xml`](https://github.com/GoogleChromeLabs/svgomg-twa/blob/master/app/src/main/AndroidManifest.xml#L71-L77) to handle things correctly. They would look something like this:
> > 
> > ```
> >  <intent-filter android:autoVerify="true">
> >      <action android:name="android.intent.action.VIEW"/>
> >      <category android:name="android.intent.category.DEFAULT" />
> >      <category android:name="android.intent.category.BROWSABLE"/>
> >      <data android:scheme="https"
> >            android:host="myexamplecost.com"
> >            android:path="/pwa1" />
> > </intent-filter>
> > `Great ! working fine
> > ```

This is not practical for 1000's PWA's. So I am generating assetliks.json dynamically as needed.

**Comment by Rogersuporte** [comment]
@andreban @PEConn, I managed to implement 28 TWAs for the same domain, it turns out that google search only indexed the first one. Is there any limit? I saw that there is an include command, do I need to split? Can you provide an example if applicable?

Thanks,
Roger
