### ISSUE TITLE
9-patch on splash screen not strech

### ISSUE THREAD

**Issue by mathcoll** [GoogleChromeLabs/svgomg-twa#71]
Hi all,

I'm not able to activate 9 patch on splash screen.
* Launcher is displaying splash screen with image not strech, a normal .png
* I created .9.png files using the Android Studio editor (a crazy tool.. :-) )

But then the image remain centered and not stretch.
Are there any additional setup to do with a TWA?

Thanks a lot.

**Comment by andreban** [comment]
This is related to #44 9 patch and SVGs are not currently supported for the splash screen.

**Comment by andreban** [comment]
Created this [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1054736) on bugs.chromium.org to track this as a feature request. 
Closing the issue here in favour of that one.
