### ISSUE TITLE
How to know when running inside the TWA vs Browser vs PWA.

### ISSUE THREAD

**Issue by azlaten** [GoogleChromeLabs/svgomg-twa#72]
Thanks for the great project.  It's awesome for us web-only guys.

My question concerns how to identify that the user is viewing the website from inside the TWA.  I know that there is a referer during the launch, but setting a cookie or local storage based upon that referer to identify the TWA in the user's session is no good because that data is shared with Chrome as well as the PWA, if installed.

Perhaps there a way to set a custom header?  I found a conversation on SO to this effect:

https://stackoverflow.com/questions/54580414/how-can-i-detect-if-my-website-is-running-inside-a-trusted-web-actvity

With this solution:

```java
    Bundle headers = new Bundle();
    headers.putString("key", "value");
    customTabsIntent.intent.putExtra(Browser.EXTRA_HEADERS, headers);
```

If we could send a custom header with the request from the TWA, or a custom user agent, it would be a breeze to identify the environment.

Maybe there is a better way that I haven't come across.

Thanks for any help!

**Comment by mhjam** [comment]
I use the referrer approach and store my "isTWA" flag in session storage. This avoids sharing that data with Chrome. I use it to add a back button to my UI only in the TWA, and I can browse my site in parallel in Chrome and in the TWA and see the back button only in the TWA, as desired.

**Comment by andreban** [comment]
> I use the referrer approach and store my "isTWA" flag in session storage. This avoids sharing that data with Chrome. I use it to add a back button to my UI only in the TWA, and I can browse my site in parallel in Chrome and in the TWA and see the back button only in the TWA, as desired.

The setting a session cooking on the first request would be my suggestion too.

**Comment by azlaten** [comment]
Thanks guys.  I thought that session storage was shared between the TWA and Chrome.  Time to give that another try.

**Comment by andreban** [comment]
The [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) is shared. A TWA behaves like another tab/window open, do it doesn't share the [sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage).

**Comment by azlaten** [comment]
Thank you again.  Just the direction we needed.

**Comment by alex2844** [comment]
In chrome os the referrer is empty

**Comment by alex2844** [comment]
https://github.com/GoogleChrome/android-browser-helper/issues/64

**Comment by alex2844** [comment]
https://github.com/GoogleChrome/android-browser-helper/issues/64
