### ISSUE TITLE
application close issue

### ISSUE THREAD

**Issue by amarj3142** [GoogleChromeLabs/svgomg-twa#74]
created pwa app and integrated in twa android app. now i want to exit from android app from my pwa app. how i can do that, any help. 
thanks in advance

**Comment by andreban** [comment]
Hi there. Sorry for the delay on getting back. Can you provide more details on what you did and what is going wrong?

**Comment by andreban** [comment]
Closing this issue, as it's been inactive for a month. Please, re-open if you have further details.
