### ISSUE TITLE
Lock screen orientation

### ISSUE THREAD

**Issue by Berkodev** [GoogleChromeLabs/svgomg-twa#75]
Hi,

I'm trying to figure out how to lock screen orientation to portrait (so that it doesn't switch to landscape when rotating the device) for my TWA/WebApp.

I tried locking the screen orientation both from the WebApp side (`screen.orientation.lock`) and both through the AndroidManifest (using the `android:screenOrientation` attribute), but neither of them worked. 

Would appreciate help with how to do this!

**Comment by andreban** [comment]
Locking the screen orientation is a feature that needs to be implemented on the Chrome side and is being tracked on this Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=989606. 

Please, feel free to chime in it.

Closing this bug to avoid tracking the issue in two places.
