### ISSUE TITLE
[Question]: How to do you make the icon full screen (purpose: maskable)

### ISSUE THREAD

**Issue by matthewhartman** [GoogleChromeLabs/svgomg-twa#78]
Hey There,

I'm loving this boilerplate code, it's saving me a truck ton of time - really appreciate the hard work that's been put into this :+1: 

One question I had was how do I set the icon to be full (eq in PWA: purpose: maskable).

I have attached a screenshot to demonstrate.

![example](https://user-images.githubusercontent.com/1294141/72101713-79752080-3379-11ea-8ad6-caad10777d6f.jpg)

Let me know what you guys think.

Cheers,

Matt :)

**Comment by andreban** [comment]
Hi Matthew,

Thanks for the message, we are always looking into ways of making this easier for developers.

Regarding the icon, on Android, those icons are called [Adaptive Icons][1] and they can be [generated using Android Studio][2].

Another (maybe easier) option is to use [llama-pack][3]. It's NodeJs based tool that can take a [Web Manifest][4] and generate the Android Studio project for you, **including the Adaptive icons you are looking for** (thanks to @NotWoods for this contribution).

The command-line will look something like:
```
npx GoogleChromeLabs/llama-pack#0.3.0 init --manifest https://pwa-directory.appspot.com/manifest.json
```

It will ask some questions and generate the project. You can also use the tool to build it, with:
```
npx GoogleChromeLabs/llama-pack#0.3.0 build
```

Let me know if this is easier for you. Please, file issues and feature-requests agains llama-pack if you find something is wrong or missing.

PS: The template project used by the tool is based on svgomg-twa, and we plan to maintain the one in llama-pack as the main template and, in the near future, new verions of svgomg-twa will be automatically generated using llama-pack.

[1]: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive
[2]: https://developer.android.com/studio/write/image-asset-studio#create-adaptive
[3]: https://github.com/GoogleChromeLabs/llama-pack
[4]: https://developer.mozilla.org/en-US/docs/Web/Manifest

**Comment by matthewhartman** [comment]
Thanks man! That is super helpful!! 💯💯💯
