### ISSUE TITLE
[Proposal] Integrate in-app updates

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [GoogleChromeLabs/svgomg-twa#79]
The web content inside TWA updates automatically via service worker. But sometimes the native Android TWA wrapper should be updated too. What about integrating Google Play in-app updates (https://developer.android.com/guide/playcore/in-app-updates)?

Do we want this?

Technically, TWAs can be distributed via other Android app stores different to Google Play.

How this affect the final app size?

Is it possible to make this optional via config flag?

**Comment by FluorescentHallucinogen** [comment]
@PEConn @andreban What do you think about this idea?

**Comment by andreban** [comment]
Thanks for filing this @FluorescentHallucinogen, and sorry for the delay.

I haven't been able to take a deeper look into this yet. I did experiment with TWA and App Bundles a while ago, but didn't collect data on the impact on the APK size. The project also had other libraries and code, so it might not provide a good measurement anyway. 

The interesting thing here would be having a mechanist to improve the update rate / velocity of critical updates to the native side of the TWA. Not sure what the frequency on this would be and how the tradeoff on size looks like.

I think the next step here would be for someone to experiment with this and collect data on change on the APK size. 

PS: We'll move [svgomg-twa](https://github.com/GoogleChromeLabs/svgomg-twa/) to be generated via [llama-pack](https://github.com/GoogleChromeLabs/llama-pack) in the near future. 

PS2: We're also considering unifying bug-tracking in a single place, we currently have [svgomg-twa](https://github.com/GoogleChromeLabs/svgomg-twa/), [android-browser-helper](https://github.com/GoogleChrome/android-browser-helper), [llama-pack](https://github.com/GoogleChromeLabs/llama-pack) and [Chromium bugs](https://bugs.chromium.org/p/chromium/issues/list?q=component%3AUI%3EBrowser%3EMobile%3ETrustedWebActivities&can=2). We'll probalby centralize things on the last.

**Comment by andreban** [comment]
I have created an [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1054739) to track this in Chromium Bugs. Closing it here in favour of that one.
