### ISSUE TITLE
Unresolved class FileProvider

### ISSUE THREAD

**Issue by mrbinr** [GoogleChromeLabs/svgomg-twa#80]
Hi,
In my Android Studio i have « android:name="android.support.v4.content.FileProvider" » in red because « android.support.v4.content.FileProvider » seems not existing.
I've tried to find how to fix it with androidx but without success ..

What is th e rigth way to fix it ?
Thanks,
Best Regards

Pascall

**Comment by mrbinr** [comment]
Fixed by adding dependencies implementation "androidx.appcompat:appcompat:1.1.0" and replacing  android:name="android.support.v4.content.FileProvider" by android:name="androidx.core.content.FileProvider"

**Comment by mrbinr** [comment]
in fact it not works ... this make app crashing

**Comment by andreban** [comment]
The `custom-tabs-client` support library doesn't support AndroidX. We have just [released version 1.0.0][1] of [`android-browser-helper`][3], which works with AndroidX. 

The latest version of `svgomg-twa` is already using it. Here's [the diff][3] with the changes made to convert it from using the old library to the new library.

[1]: https://developers.google.com/web/updates/2020/twa-android-browser-helper
[2]: https://github.com/GoogleChromeLabs/svgomg-twa/pull/76/files
[3]: https://github.com/GoogleChrome/android-browser-helper

**Comment by mrbinr** [comment]
Thanks a lot
