### ISSUE TITLE
How to remove toaster « Running in chrome » ?

### ISSUE THREAD

**Issue by mrbinr** [GoogleChromeLabs/svgomg-twa#81]
Hi,
Is there a solution to remove bottom toaster « Running in Chrome » displayed when app for the first time ?

Thanks
Best Regards
Pascall

**Comment by andreban** [comment]
The "Running in Chrome" message is implemented on the Chrome side, so it is not really an issue on the sample project.

Work to improve it is being tracked on this Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=981323. Please, feel free to chime in it.

Closing this bug to avoid tracking the issue in two places.
