### ISSUE TITLE
White line between navigation bar and main content

### ISSUE THREAD

**Issue by lukestateson** [GoogleChromeLabs/svgomg-twa#82]
When setting navigationColor to any dark color I've noticed the white line between nav bar and main content window.

PWA app installed directly from browser does not have this line. Other native apps don't have this line either. 

It is only visible when installing an APK.

Is it possible to make it the same color as navigation bar?

Here's a screenshot:

![Image](https://i.imgur.com/1wqMvfp.jpg)

**Comment by andreban** [comment]
Thanks for filing this, @lukestateson 

This needs to be implemented on the Chrome side, and is outside the scope of the SVGOMG demo. It is being tracked on this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1021436

Feel free to chime in on the issue. I'm closing this one to avoid tracking the same issue in 2 different places.
