### ISSUE TITLE
Data interface between native code and JavaScript and plug-in system

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [GoogleChromeLabs/svgomg-twa#84]
I need to implement background geolocation that currently not supported in Web. So I plan to implement it natively. But how to pass data from native code to JavaScript (and vice versa)?

Is there standardized data interface (bridge) between native code and JavaScript?

One of the best things about Cordova is plug-ins (native code modules) + big catalog of third-party plugins published and distributed via NPM (https://cordova.apache.org/plugins/). It would be nice to have a plug-in system something like in Cordova.

**Comment by FluorescentHallucinogen** [comment]
Is it possible to override (polyfill/shim) `navigator.geolocation` or [`GeolocationSensor`](https://w3c.github.io/geolocation-sensor/) in TWA to use native code implementation?

**Comment by andreban** [comment]
There isn't a data interface, at the moment, but this is something we frequently review. This issue https://github.com/GoogleChrome/android-browser-helper/issues/55 has more details.

Can you give more details on the use-case background geolocation is being used for?

**Comment by FluorescentHallucinogen** [comment]
My use-case is driver's taximeter for taxi PWA that should still calculates passenger fares based on distance travelled even if the screen off or the app minimized.

Other use-cases:

https://w3c.github.io/geolocation-sensor/#use-cases-background-continuous

https://w3c.github.io/geolocation-sensor/#use-cases-background-geofence

**Comment by andreban** [comment]
Closing the issue here, in favour of tracking it in GoogleChrome/android-browser-helper#55
