### ISSUE TITLE
Using FCM message/pushNotification to TWA

### ISSUE THREAD

**Issue by mathcoll** [GoogleChromeLabs/svgomg-twa#87]
Hi team,

I have a TWA using "enableNotification" = true in the build.gradle
I can successfully send FCM message from Firebase account; and they are received on the App.
I'm also able to send successfully pushNotification from webpush GCM (from my own server); but those pushNotification seems only received from the web, not the App (I guess that's on purpose, right ?)

My goal would be to send (and receive) FCM from my server.
I've tried to install "firebase-admin" (I'm running a node script on server) ; seems the setting are correct, but I really don't understand where can I find the "registrationTokens" from the TWA ?
Additionally, all online resources refers to full-native apps.. so I can't get it to work as I'm not able to find the tokens.

I know I probably messing up and mixing multiple things, and any help would be appreciated to clear that up.
Cheers.

**Comment by andreban** [comment]
Hi @mathcoll 

On TWAs, push notifications will work just like in the web. No need to write native code for it to work. This is the documentation for using web push with firebase: https://firebase.google.com/docs/cloud-messaging/js/client

**Comment by andreban** [comment]
Closing this issue, as it's been inactive for almost a month. The best place to ask trusted web activity questions is on StackOverflow, on the [trusted-web-activity](https://stackoverflow.com/questions/tagged/trusted-web-activity) tag.
