### ISSUE TITLE
Support Splash Screen?

### ISSUE THREAD

**Issue by uwolfer** [GoogleChromeLabs/svgomg-twa#9]
When I add a PWA to homescreen with Chrome on Android, an APK is generated which displays the splash screen as defined in the manifest file.

Is there an easy way to define a splash screen with TWA? It displays a white screen currently (as defined [here](https://github.com/GoogleChromeLabs/svgomg-twa/blob/master/app/src/main/res/values/styles.xml#L18)).

**Comment by BamiGorengo** [comment]
An automaticly usage of the webmanifest would be awesome. but if this isnt possible a predefined default styling which is easy to customize would be awesome here.

**Comment by Buom01** [comment]
I have a partial solution:
Set the default view and arrange it to make it show  like a splashscreen. It will be showed when chrome is launching.
It works quite good for me, but there are a white flickering when chrome is opening and loading page

But it permit to keep the status-bar's color stable and is quite simple to set up.

[Creating a gist...........]

---

Else I suppose that you should look to Apache's Cordova splashscreen package, maybe it could help you to develop one for TWA, (it's only an idea)

**Comment by andreban** [comment]
Chrome 75 will support Splash Screens. We have added support for the markup needed on #23.

**Comment by odahcam** [comment]
For anyone in the future looking for a "how to", here it goes: https://developers.google.com/web/updates/2019/02/using-twa#add-splash-markup
