### ISSUE TITLE
App Shortcut Error

### ISSUE THREAD

**Issue by dwaring87** [GoogleChromeLabs/svgomg-twa#90]
When starting an app shortcut, I get either a "permission denied" error or "app not installed" error, depending on the phone.  I think the intent target class needs to be updated to `com.google.androidbrowserhelper.trusted.LauncherActivity`

https://github.com/GoogleChromeLabs/svgomg-twa/blob/a3296efcdbc64819126c290186f45569dad7a317/app/build.gradle#L150

**Comment by andreban** [comment]
@rayankans would you know what may be happening?

**Comment by rayankans** [comment]
I'm not sure, I'm unable to repro. @PEConn Do you know what the right target class should be?

**Comment by PEConn** [comment]
I think @dwaring87  is correct, although I'm surprised @rayankans is unable to reproduce.

@rayankans are you creating the app with `svgomg-twa` or with `llama-pack`? (It looks like both of them have this error in though).

The targetClass here needs to match up with an Activity in AndroidManifest, and in both [svgomg-twa][1] and [llama-pack][2], this is `com.google.androidbrowserhelper.trusted.LauncherActivity`.

[1]: https://github.com/GoogleChromeLabs/svgomg-twa/blob/master/app/src/main/AndroidManifest.xml#L39
[2]: https://github.com/GoogleChromeLabs/llama-pack/blob/7bbed5bff23c0755e58cbeaabe2f540a816cbef1/template_project/app/src/main/AndroidManifest.xml#L46

**Comment by rayankans** [comment]
According to @andreban's comment [here](https://github.com/GoogleChromeLabs/llama-pack/pull/99#discussion_r376483601), this should have been updated to `com.google.androidbrowserhelper.trusted.LauncherActivity` after the migration to `androix.browser-1.2.0`.

**Comment by andreban** [comment]
#92 should fixes the demo code. @dwaring87 Could you try changing this in your app and let us know if it fixes the issue?

**Comment by dwaring87** [comment]
@andreban updating the target class does fix the issue for me.
