### ISSUE TITLE
URL bar still present when released

### ISSUE THREAD

**Issue by kondulak10** [GoogleChromeLabs/svgomg-twa#93]
Hello,
Testing on: Redmi Note 7, Chrome 79.0,3945.136
- PWA working by itself from the browser
- Deployed to Play store
- Assetlinks SHA same as App signing certificate
- Connection tested in Console 

But the URL bar still remains there.

![Screenshot_2020-02-11-19-13-07-278_dev conn assetlinkstool](https://user-images.githubusercontent.com/2103269/74266693-03136780-4d05-11ea-8719-cb34e3ceae7f.jpg)

![Screenshot_2020-02-11-19-13-19-362_com android chrome](https://user-images.githubusercontent.com/2103269/74266697-03abfe00-4d05-11ea-9b49-61b7ea921251.jpg)

https://storyheim.com/.well-known/assetlinks.json

Is there any other possible reason for that? I went through the forums and did not find anything else.

**Comment by kondulak10** [comment]
I got it remotely tested by other people on S9 and J530F and the URL bar is not apparently there. Does it have to do something with the versions of something?

**Comment by andreban** [comment]
Would you mind trying to clear Chrome data and retry?  I'm wondering if
theres something cached.

**Comment by kondulak10** [comment]
Thank you very much! We have been stuck on that for a month and it is a first time I hear about this as a potential issue. Deleting the whole Chrome data solved it.
