### ISSUE TITLE
TWA Throwing Error - android.app.RemoteServiceException

### ISSUE THREAD

**Issue by naveedahmed1** [GoogleChromeLabs/svgomg-twa#95]
I am seeing crash reports in Play Console with latest version of TWA which is based on `svgomg-twa`

```
android.app.RemoteServiceException

android.app.ActivityThread$H.handleMessage

Today, 1:29 AM on app version 100171
Samsung Galaxy Grand Prime (fortuna3g), Android 5.0

android.app.RemoteServiceException: 
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1556)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:135)
  at android.app.ActivityThread.main (ActivityThread.java:5753)
  at java.lang.reflect.Method.invoke (Method.java)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1405)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1200)
```

**Reports by Devices**:
**Galaxy Grand Prime (fortuna3g)**:10
**Galaxy S4 (jflte):** 4

**Comment by rockeynebhwani** [comment]
@andreban  / @PEConn  - +1 on this issue from my side. We are also seeing this for George TWA app. Here is OS / device breakdown

![image](https://user-images.githubusercontent.com/1718757/74486711-7a87f900-4eb5-11ea-94e2-8e083d501bc6.png)

**Comment by andreban** [comment]
Would you mind filing this bug in bugs.chromium.org, under this component: https://bugs.chromium.org/p/chromium/issues/list?q=component%3AUI%3EBrowser%3EMobile%3ETrustedWebActivities&can=2 ?

**Comment by naveedahmed1** [comment]
Thank you so much @andreban I have filed the bug here https://bugs.chromium.org/p/chromium/issues/detail?id=1052365&can=2&q=component%3AUI%3EBrowser%3EMobile%3ETrustedWebActivities

Somehow it seems that the category isn't properly assigned, the components list doesn't show category of `component:UI>Browser>Mobile>TrustedWebActivities`. Its only showing `Blink` components.

**Comment by andreban** [comment]
@naveedahmed1 I have added the component to the bug.

**Comment by naveedahmed1** [comment]
Thank you so much @andreban :)

**Comment by naveedahmed1** [comment]
@andreban this is what they are saying:

https://bugs.chromium.org/p/chromium/issues/detail?id=1052365#c5
> The issue seems to be out of our triaging scope as it is related to TWA which is based on svgomg-twa. Hence, adding label TE-NeedsTriageHelp for further investigation from dev team.
> 
> Thanks...!!

Does this mean that its something that needs to be resolved in this repo?

**Comment by andreban** [comment]
This repository doesn't contain any Java code and just uses code that is part of android-browser-helper. We're centralising issues on bugs.chromium.org, as we're getting duplicated issues across many surfaces. Closing the issue here in favour of bugs.chromium.org.
